#############################################################################
# Makefile for building: bomberman.app/Contents/MacOS/bomberman
# Generated by qmake (3.1) (Qt 5.14.0)
# Project:  bomberman.pro
# Template: app
# Command: /usr/local/opt/qt/bin/qmake -o Makefile bomberman.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.14.0/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.14.0/lib
QMAKE         = /usr/local/opt/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/opt/qt/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/opt/qt/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = bomberman1.0.0
DISTDIR = /Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman/.tmp/bomberman1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.14.0/lib -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qrc_res.cpp \
		affichage/qrc_res.cpp \
		basics/bloc.cpp \
		basics/bomb.cpp \
		basics/display.cpp \
		basics/game.cpp \
		basics/item.cpp \
		basics/main.cpp \
		basics/map.cpp \
		basics/player.cpp \
		basics/test.cpp \
		fck/bloc.cpp \
		fck/bomb.cpp \
		fck/main.cpp \
		fck/map.cpp \
		fck/player.cpp \
		affichage/Sources/Bloc.cpp \
		affichage/Sources/Bomb.cpp \
		affichage/Sources/Button.cpp \
		affichage/Sources/Game.cpp \
		affichage/Sources/main.cpp \
		affichage/Sources/Map.cpp \
		affichage/Sources/Player.cpp qrc_res.cpp \
		moc_Bomb.cpp \
		moc_Button.cpp \
		moc_Game.cpp \
		moc_Player.cpp
OBJECTS       = qrc_res.o \
		qrc_res.o \
		bloc.o \
		bomb.o \
		display.o \
		game.o \
		item.o \
		main.o \
		map.o \
		player.o \
		test.o \
		bloc.o \
		bomb.o \
		main.o \
		map.o \
		player.o \
		Bloc.o \
		Bomb.o \
		Button.o \
		Game.o \
		main.o \
		Map.o \
		Player.o \
		qrc_res.o \
		moc_Bomb.o \
		moc_Button.o \
		moc_Game.o \
		moc_Player.o
DIST          = /usr/local/Cellar/qt/5.14.0/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/lex.prf \
		bomberman.pro basics/bloc.hpp \
		basics/bomb.hpp \
		basics/display.hpp \
		basics/game.hpp \
		basics/item.hpp \
		basics/map.hpp \
		basics/player.hpp \
		fck/bloc.hpp \
		fck/bomb.hpp \
		fck/map.hpp \
		fck/player.hpp \
		affichage/Headers/Bloc.hpp \
		affichage/Headers/Bomb.hpp \
		affichage/Headers/Button.hpp \
		affichage/Headers/Game.hpp \
		affichage/Headers/Map.hpp \
		affichage/Headers/Player.hpp qrc_res.cpp \
		affichage/qrc_res.cpp \
		basics/bloc.cpp \
		basics/bomb.cpp \
		basics/display.cpp \
		basics/game.cpp \
		basics/item.cpp \
		basics/main.cpp \
		basics/map.cpp \
		basics/player.cpp \
		basics/test.cpp \
		fck/bloc.cpp \
		fck/bomb.cpp \
		fck/main.cpp \
		fck/map.cpp \
		fck/player.cpp \
		affichage/Sources/Bloc.cpp \
		affichage/Sources/Bomb.cpp \
		affichage/Sources/Button.cpp \
		affichage/Sources/Game.cpp \
		affichage/Sources/main.cpp \
		affichage/Sources/Map.cpp \
		affichage/Sources/Player.cpp
QMAKE_TARGET  = bomberman
DESTDIR       = 
TARGET        = bomberman.app/Contents/MacOS/bomberman

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx10.15
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman/bomberman.pro


include /usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

bomberman.app/Contents/MacOS/bomberman:  $(OBJECTS)  
	@test -d bomberman.app/Contents/MacOS/ || mkdir -p bomberman.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: bomberman.pro /usr/local/Cellar/qt/5.14.0/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.14.0/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.14.0/mkspecs/features/lex.prf \
		bomberman.pro \
		affichage/res.qrc \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile bomberman.pro
/usr/local/Cellar/qt/5.14.0/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.14.0/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.14.0/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.14.0/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.14.0/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.14.0/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.14.0/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.14.0/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.14.0/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3drender.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3drender_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/resources_functions.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.14.0/mkspecs/features/lex.prf:
bomberman.pro:
affichage/res.qrc:
/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile bomberman.pro

qmake_all: FORCE

bomberman.app/Contents/PkgInfo: 
	@test -d bomberman.app/Contents || mkdir -p bomberman.app/Contents
	@$(DEL_FILE) bomberman.app/Contents/PkgInfo
	@echo "APPL????" > bomberman.app/Contents/PkgInfo
bomberman.app/Contents/Resources/empty.lproj: 
	@test -d bomberman.app/Contents/Resources || mkdir -p bomberman.app/Contents/Resources
	@touch bomberman.app/Contents/Resources/empty.lproj
	
bomberman.app/Contents/Info.plist: 
	@test -d bomberman.app/Contents || mkdir -p bomberman.app/Contents
	@$(DEL_FILE) bomberman.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,e.bomberman,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},e.bomberman,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,bomberman,g" -e "s,@LIBRARY@,bomberman,g" -e "s,\$${EXECUTABLE_NAME},bomberman,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/Cellar/qt/5.14.0/mkspecs/macx-clang/Info.plist.app >bomberman.app/Contents/Info.plist

all: Makefile \
		bomberman.app/Contents/PkgInfo \
		bomberman.app/Contents/Resources/empty.lproj \
		bomberman.app/Contents/Info.plist bomberman.app/Contents/MacOS/bomberman

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents affichage/res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.14.0/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents basics/bloc.hpp basics/bomb.hpp basics/display.hpp basics/game.hpp basics/item.hpp basics/map.hpp basics/player.hpp fck/bloc.hpp fck/bomb.hpp fck/map.hpp fck/player.hpp affichage/Headers/Bloc.hpp affichage/Headers/Bomb.hpp affichage/Headers/Button.hpp affichage/Headers/Game.hpp affichage/Headers/Map.hpp affichage/Headers/Player.hpp $(DISTDIR)/
	$(COPY_FILE) --parents qrc_res.cpp affichage/qrc_res.cpp basics/bloc.cpp basics/bomb.cpp basics/display.cpp basics/game.cpp basics/item.cpp basics/main.cpp basics/map.cpp basics/player.cpp basics/test.cpp fck/bloc.cpp fck/bomb.cpp fck/main.cpp fck/map.cpp fck/player.cpp affichage/Sources/Bloc.cpp affichage/Sources/Bomb.cpp affichage/Sources/Button.cpp affichage/Sources/Game.cpp affichage/Sources/main.cpp affichage/Sources/Map.cpp affichage/Sources/Player.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r bomberman.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: affichage/res.qrc \
		/usr/local/Cellar/qt/5.14.0/bin/rcc \
		affichage/Resources/Player/Player_1_dead.png \
		affichage/Resources/Player/Player_5_left.png \
		affichage/Resources/Player/Player_5_right.png \
		affichage/Resources/Player/Player_1_left.png \
		affichage/Resources/Player/Player_2_dead.png \
		affichage/Resources/Player/Player_2_left.png \
		affichage/Resources/Player/Player_1_centre.png \
		affichage/Resources/Player/Player_3_dead.png \
		affichage/Resources/Player/Player_2_centre.png \
		affichage/Resources/Player/Player_1_right.png \
		affichage/Resources/Player/Player_3_left.png \
		affichage/Resources/Player/Player_3_centre.png \
		affichage/Resources/Player/Player_4_dead.png \
		affichage/Resources/Player/Player_4_centre.png \
		affichage/Resources/Player/Player_2_right.png \
		affichage/Resources/Player/Player_3_right.png \
		affichage/Resources/Player/Player_5_dead.png \
		affichage/Resources/Player/Player_4_right.png \
		affichage/Resources/Player/Player_4_left.png \
		affichage/Resources/Player/Player_5_centre.png \
		affichage/Resources/bombitrouille/BBT_Exp_4.png \
		affichage/Resources/bombitrouille/BBT_Blast_1.png \
		affichage/Resources/bombitrouille/BBT_Exp_3.png \
		affichage/Resources/bombitrouille/BBT_Exp_2.png \
		affichage/Resources/bombitrouille/BBT_Exp_6.png \
		affichage/Resources/bombitrouille/BBT_flashing_2.png \
		affichage/Resources/bombitrouille/BBT_Blast_3.png \
		affichage/Resources/bombitrouille/BBT_Exp_1.png \
		affichage/Resources/bombitrouille/BBT_Exp_5.png \
		affichage/Resources/bombitrouille/BBT_flashing_1.png \
		affichage/Resources/bombitrouille/BBT_Blast_2.png \
		affichage/Resources/Menu/Menu.png \
		affichage/Resources/Menu/Start.png \
		affichage/Resources/Menu/Quit.png \
		affichage/Resources/Menu/Title.png \
		affichage/Resources/Menu/character_name_Po.png \
		affichage/Resources/Menu/option.png \
		affichage/Resources/Classic_bomb/Bomb_Exploding_3.png \
		affichage/Resources/Classic_bomb/blast_2.png \
		affichage/Resources/Classic_bomb/Bomb_Exploding_2.png \
		affichage/Resources/Classic_bomb/Bomb_Exploding_6.png \
		affichage/Resources/Classic_bomb/Bomb_Flashing_2.png \
		affichage/Resources/Classic_bomb/blast_1.png \
		affichage/Resources/Classic_bomb/Bomb_Exploding_1.png \
		affichage/Resources/Classic_bomb/Bomb_Exploding_5.png \
		affichage/Resources/Classic_bomb/Bomb_Flashing_1.png \
		affichage/Resources/Classic_bomb/Bomb_Exploding_4.png \
		affichage/Resources/Classic_bomb/blast_3.png \
		affichage/Resources/Music/01_The_Day_Is_My_Enemy.m4a \
		affichage/Resources/Land/Sol.png
	/usr/local/Cellar/qt/5.14.0/bin/rcc -name res affichage/res.qrc -o qrc_res.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/5.14.0/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/Cellar/qt/5.14.0/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Bomb.cpp moc_Button.cpp moc_Game.cpp moc_Player.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Bomb.cpp moc_Button.cpp moc_Game.cpp moc_Player.cpp
moc_Bomb.cpp: affichage/Headers/Bomb.hpp \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/QSize \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/qsize.h \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/qpixmap.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.14.0/bin/moc
	/usr/local/Cellar/qt/5.14.0/bin/moc $(DEFINES) --include /Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman/moc_predefs.h -I/usr/local/Cellar/qt/5.14.0/mkspecs/macx-clang -I/Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman -I/Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman -I/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/usr/local/Cellar/qt/5.14.0/lib affichage/Headers/Bomb.hpp -o moc_Bomb.cpp

moc_Button.cpp: affichage/Headers/Button.hpp \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.14.0/bin/moc
	/usr/local/Cellar/qt/5.14.0/bin/moc $(DEFINES) --include /Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman/moc_predefs.h -I/usr/local/Cellar/qt/5.14.0/mkspecs/macx-clang -I/Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman -I/Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman -I/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/usr/local/Cellar/qt/5.14.0/lib affichage/Headers/Button.hpp -o moc_Button.cpp

moc_Game.cpp: affichage/Headers/Game.hpp \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/QBrush \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/qbrush.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.14.0/bin/moc
	/usr/local/Cellar/qt/5.14.0/bin/moc $(DEFINES) --include /Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman/moc_predefs.h -I/usr/local/Cellar/qt/5.14.0/mkspecs/macx-clang -I/Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman -I/Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman -I/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/usr/local/Cellar/qt/5.14.0/lib affichage/Headers/Game.hpp -o moc_Game.cpp

moc_Player.cpp: affichage/Headers/Player.hpp \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/QKeyEvent \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/QSize \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/qsize.h \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/qstring.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.14.0/bin/moc
	/usr/local/Cellar/qt/5.14.0/bin/moc $(DEFINES) --include /Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman/moc_predefs.h -I/usr/local/Cellar/qt/5.14.0/mkspecs/macx-clang -I/Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman -I/Users/maxencenaud/Desktop/Programmation/2A/IN204/Projet/bomberman -I/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/usr/local/Cellar/qt/5.14.0/lib affichage/Headers/Player.hpp -o moc_Player.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

qrc_res.o: affichage/qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o affichage/qrc_res.cpp

bloc.o: basics/bloc.cpp basics/bloc.hpp \
		basics/bomb.hpp \
		basics/map.hpp \
		basics/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bloc.o basics/bloc.cpp

bomb.o: basics/bomb.cpp basics/bomb.hpp \
		basics/map.hpp \
		basics/bloc.hpp \
		basics/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bomb.o basics/bomb.cpp

display.o: basics/display.cpp basics/display.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o display.o basics/display.cpp

game.o: basics/game.cpp basics/game.hpp \
		basics/player.hpp \
		basics/bloc.hpp \
		basics/bomb.hpp \
		basics/map.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o basics/game.cpp

item.o: basics/item.cpp basics/item.hpp \
		basics/bloc.hpp \
		basics/bomb.hpp \
		basics/map.hpp \
		basics/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o item.o basics/item.cpp

main.o: basics/main.cpp basics/player.hpp \
		basics/bloc.hpp \
		basics/bomb.hpp \
		basics/map.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o basics/main.cpp

map.o: basics/map.cpp basics/map.hpp \
		basics/bloc.hpp \
		basics/bomb.hpp \
		basics/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o map.o basics/map.cpp

player.o: basics/player.cpp basics/player.hpp \
		basics/bloc.hpp \
		basics/bomb.hpp \
		basics/map.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o basics/player.cpp

test.o: basics/test.cpp basics/display.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o basics/test.cpp

bloc.o: fck/bloc.cpp fck/bloc.hpp \
		fck/player.hpp \
		fck/bomb.hpp \
		fck/map.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bloc.o fck/bloc.cpp

bomb.o: fck/bomb.cpp fck/bomb.hpp \
		fck/player.hpp \
		fck/bloc.hpp \
		fck/map.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bomb.o fck/bomb.cpp

main.o: fck/main.cpp fck/player.hpp \
		fck/map.hpp \
		fck/bloc.hpp \
		fck/bomb.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o fck/main.cpp

map.o: fck/map.cpp fck/map.hpp \
		fck/bloc.hpp \
		fck/player.hpp \
		fck/bomb.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o map.o fck/map.cpp

player.o: fck/player.cpp fck/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o fck/player.cpp

Bloc.o: affichage/Sources/Bloc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bloc.o affichage/Sources/Bloc.cpp

Bomb.o: affichage/Sources/Bomb.cpp /usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bomb.o affichage/Sources/Bomb.cpp

Button.o: affichage/Sources/Button.cpp /usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/QSize \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/qsize.h \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/QIcon \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/qicon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Button.o affichage/Sources/Button.cpp

Game.o: affichage/Sources/Game.cpp /usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/QColor \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/qcolor.h \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/QFont \
		/usr/local/Cellar/qt/5.14.0/lib/QtGui.framework/Headers/qfont.h \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Game.o affichage/Sources/Game.cpp

main.o: affichage/Sources/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o affichage/Sources/main.cpp

Map.o: affichage/Sources/Map.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Map.o affichage/Sources/Map.cpp

Player.o: affichage/Sources/Player.cpp /usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.14.0/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o affichage/Sources/Player.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_Bomb.o: moc_Bomb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Bomb.o moc_Bomb.cpp

moc_Button.o: moc_Button.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Button.o moc_Button.cpp

moc_Game.o: moc_Game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Game.o moc_Game.cpp

moc_Player.o: moc_Player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Player.o moc_Player.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

